/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ECMSMONITOR } from './ECMSMONITOR';
import { ECMSPL } from './ECMSPL';
import { HttpFile } from '../http/http';

export class BCMSMAIN {
    'mainId'?: number;
    'idPl'?: number;
    'monitorId'?: number;
    'dateFrom'?: Date;
    'dateTo'?: Date;
    'timeFrom'?: Date;
    'timeTo'?: Date;
    'readonly'?: boolean;
    'type'?: number;
    'providerId'?: number;
    'playlist'?: ECMSPL;
    'monitor'?: ECMSMONITOR;
    'allPlaylists'?: { [key: string]: string; };
    'allMonitors'?: { [key: string]: string; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mainId",
            "baseName": "mainId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "idPl",
            "baseName": "idPl",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "monitorId",
            "baseName": "monitorId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "dateFrom",
            "baseName": "dateFrom",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateTo",
            "baseName": "dateTo",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "timeFrom",
            "baseName": "timeFrom",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "timeTo",
            "baseName": "timeTo",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "readonly",
            "baseName": "readonly",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "providerId",
            "baseName": "providerId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "playlist",
            "baseName": "playlist",
            "type": "ECMSPL",
            "format": ""
        },
        {
            "name": "monitor",
            "baseName": "monitor",
            "type": "ECMSMONITOR",
            "format": ""
        },
        {
            "name": "allPlaylists",
            "baseName": "allPlaylists",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "allMonitors",
            "baseName": "allMonitors",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BCMSMAIN.attributeTypeMap;
    }

    public constructor() {
    }
}

