/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CouponSchemaBean } from './CouponSchemaBean';
import { HttpFile } from '../http/http';

export class CouponAusgabeBean {
    'schema'?: CouponSchemaBean;
    'id'?: string;
    'lfdNr'?: number;
    'ausgabeApoNr'?: number;
    'status'?: number;
    'ausgabeDatum'?: string;
    'bedNr'?: string;
    'bedKurz'?: string;
    'aplNr'?: string;
    'aplKurz'?: string;
    'anzahl'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "schema",
            "type": "CouponSchemaBean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "lfdNr",
            "baseName": "lfdNr",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "ausgabeApoNr",
            "baseName": "ausgabeApoNr",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "ausgabeDatum",
            "baseName": "ausgabeDatum",
            "type": "string",
            "format": ""
        },
        {
            "name": "bedNr",
            "baseName": "bedNr",
            "type": "string",
            "format": ""
        },
        {
            "name": "bedKurz",
            "baseName": "bedKurz",
            "type": "string",
            "format": ""
        },
        {
            "name": "aplNr",
            "baseName": "aplNr",
            "type": "string",
            "format": ""
        },
        {
            "name": "aplKurz",
            "baseName": "aplKurz",
            "type": "string",
            "format": ""
        },
        {
            "name": "anzahl",
            "baseName": "anzahl",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return CouponAusgabeBean.attributeTypeMap;
    }

    public constructor() {
    }
}

