/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CouponSchemaBean {
    'schemaApoNr'?: number;
    'schemaId'?: string;
    'schemaVersion'?: number;
    'schemaTyp'?: number;
    'schemaEntst'?: string;
    'status'?: number;
    'name'?: string;
    'beschreibung'?: string;
    'regelnAusgabe'?: string;
    'regelnEinloesung'?: string;
    'bedNr'?: string;
    'bedKurz'?: string;
    'gueltigVon'?: Date;
    'gueltigBis'?: Date;
    'gueterGueltigVon'?: Date;
    'gueterGueltigBis'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schemaApoNr",
            "baseName": "schemaApoNr",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "schemaId",
            "baseName": "schemaId",
            "type": "string",
            "format": ""
        },
        {
            "name": "schemaVersion",
            "baseName": "schemaVersion",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "schemaTyp",
            "baseName": "schemaTyp",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "schemaEntst",
            "baseName": "schemaEntst",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "beschreibung",
            "baseName": "beschreibung",
            "type": "string",
            "format": ""
        },
        {
            "name": "regelnAusgabe",
            "baseName": "regelnAusgabe",
            "type": "string",
            "format": ""
        },
        {
            "name": "regelnEinloesung",
            "baseName": "regelnEinloesung",
            "type": "string",
            "format": ""
        },
        {
            "name": "bedNr",
            "baseName": "bedNr",
            "type": "string",
            "format": ""
        },
        {
            "name": "bedKurz",
            "baseName": "bedKurz",
            "type": "string",
            "format": ""
        },
        {
            "name": "gueltigVon",
            "baseName": "gueltigVon",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "gueltigBis",
            "baseName": "gueltigBis",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "gueterGueltigVon",
            "baseName": "gueterGueltigVon",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "gueterGueltigBis",
            "baseName": "gueterGueltigBis",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return CouponSchemaBean.attributeTypeMap;
    }

    public constructor() {
    }
}

