/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ECMSMONITOR } from './ECMSMONITOR';
import { ECMSPHARMACY } from './ECMSPHARMACY';
import { HttpFile } from '../http/http';

export class ECMSSTATION {
    'id'?: number;
    'stationName'?: string;
    'computerName'?: string;
    'socketHostname'?: string;
    'socketPort'?: number;
    'monitors'?: Array<ECMSMONITOR>;
    'pharmacy'?: ECMSPHARMACY;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "stationName",
            "baseName": "stationName",
            "type": "string",
            "format": ""
        },
        {
            "name": "computerName",
            "baseName": "computerName",
            "type": "string",
            "format": ""
        },
        {
            "name": "socketHostname",
            "baseName": "socketHostname",
            "type": "string",
            "format": ""
        },
        {
            "name": "socketPort",
            "baseName": "socketPort",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "monitors",
            "baseName": "monitors",
            "type": "Array<ECMSMONITOR>",
            "format": ""
        },
        {
            "name": "pharmacy",
            "baseName": "pharmacy",
            "type": "ECMSPHARMACY",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ECMSSTATION.attributeTypeMap;
    }

    public constructor() {
    }
}

