/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ECMSPHARMACY {
    'pharmacyId'?: number;
    'pharmacyExternalId'?: string;
    'pharmacyName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pharmacyId",
            "baseName": "pharmacyId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "pharmacyExternalId",
            "baseName": "pharmacyExternalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "pharmacyName",
            "baseName": "pharmacyName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ECMSPHARMACY.attributeTypeMap;
    }

    public constructor() {
    }
}

