/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ECMSCONDITIONEXTDATA {
    'conditionId'?: number;
    'extId'?: string;
    'additionalExtData'?: string;
    'crosselerPznList'?: string;
    'crosselerName'?: string;
    'crosselerValidFrom'?: Date;
    'crosselerValidTo'?: Date;
    'crosselerReleased'?: boolean;
    'crosselerCreationDate'?: Date;
    'providerId'?: number;
    'providerName'?: string;
    'groupId'?: number;
    'groupName'?: string;
    'defaultInGroup'?: boolean;
    'shortDescription'?: string;
    'longDescription'?: string;
    'userMediaFilePath'?: string;
    'originalShortDescription'?: string;
    'originalLongDescription'?: string;
    'originalUserMediaFilePath'?: string;
    'originalConditionXML'?: string;
    'crossSellerPhXML'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conditionId",
            "baseName": "conditionId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "extId",
            "baseName": "extId",
            "type": "string",
            "format": ""
        },
        {
            "name": "additionalExtData",
            "baseName": "additionalExtData",
            "type": "string",
            "format": ""
        },
        {
            "name": "crosselerPznList",
            "baseName": "crosselerPznList",
            "type": "string",
            "format": ""
        },
        {
            "name": "crosselerName",
            "baseName": "crosselerName",
            "type": "string",
            "format": ""
        },
        {
            "name": "crosselerValidFrom",
            "baseName": "crosselerValidFrom",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "crosselerValidTo",
            "baseName": "crosselerValidTo",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "crosselerReleased",
            "baseName": "crosselerReleased",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "crosselerCreationDate",
            "baseName": "crosselerCreationDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "providerId",
            "baseName": "providerId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "providerName",
            "baseName": "providerName",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "groupName",
            "baseName": "groupName",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultInGroup",
            "baseName": "defaultInGroup",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "shortDescription",
            "baseName": "shortDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "longDescription",
            "baseName": "longDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "userMediaFilePath",
            "baseName": "userMediaFilePath",
            "type": "string",
            "format": ""
        },
        {
            "name": "originalShortDescription",
            "baseName": "originalShortDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "originalLongDescription",
            "baseName": "originalLongDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "originalUserMediaFilePath",
            "baseName": "originalUserMediaFilePath",
            "type": "string",
            "format": ""
        },
        {
            "name": "originalConditionXML",
            "baseName": "originalConditionXML",
            "type": "string",
            "format": ""
        },
        {
            "name": "crossSellerPhXML",
            "baseName": "crossSellerPhXML",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ECMSCONDITIONEXTDATA.attributeTypeMap;
    }

    public constructor() {
    }
}

