/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ECMSPL } from './ECMSPL';
import { ECMSSTATION } from './ECMSSTATION';
import { HttpFile } from '../http/http';

export class ECMSMONITOR {
    'monitorId'?: number;
    'monitorExternalId'?: string;
    'stationId'?: number;
    'screenWidth'?: number;
    'screenHeight'?: number;
    'customerDefault'?: boolean;
    'touchable'?: boolean;
    'showTotal'?: boolean;
    'description'?: string;
    'disabled'?: boolean;
    'disabledFromKti'?: boolean;
    'mainMonitor'?: boolean;
    'deviceKey'?: string;
    'adaptor'?: string;
    'ignoreCentralMainlist'?: boolean;
    'station'?: ECMSSTATION;
    'playlists'?: Array<ECMSPL>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "monitorId",
            "baseName": "monitorId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "monitorExternalId",
            "baseName": "monitorExternalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "stationId",
            "baseName": "stationId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "screenWidth",
            "baseName": "screenWidth",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "screenHeight",
            "baseName": "screenHeight",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "customerDefault",
            "baseName": "customerDefault",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "touchable",
            "baseName": "touchable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "showTotal",
            "baseName": "showTotal",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "disabled",
            "baseName": "disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "disabledFromKti",
            "baseName": "disabledFromKti",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "mainMonitor",
            "baseName": "mainMonitor",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deviceKey",
            "baseName": "deviceKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "adaptor",
            "baseName": "adaptor",
            "type": "string",
            "format": ""
        },
        {
            "name": "ignoreCentralMainlist",
            "baseName": "ignoreCentralMainlist",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "station",
            "baseName": "station",
            "type": "ECMSSTATION",
            "format": ""
        },
        {
            "name": "playlists",
            "baseName": "playlists",
            "type": "Array<ECMSPL>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ECMSMONITOR.attributeTypeMap;
    }

    public constructor() {
    }
}

