/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StatisticsMediaPlay } from './StatisticsMediaPlay';
import { HttpFile } from '../http/http';

export class MediaStatisticsResponse {
    'mediaStatistics'?: Array<StatisticsMediaPlay>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mediaStatistics",
            "baseName": "mediaStatistics",
            "type": "Array<StatisticsMediaPlay>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MediaStatisticsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

