/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StationServiceBean } from './StationServiceBean';
import { HttpFile } from '../http/http';

export class MergeWorkstationRequest {
    'station'?: StationServiceBean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "station",
            "baseName": "station",
            "type": "StationServiceBean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MergeWorkstationRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

