/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BCMSITEMPL } from './BCMSITEMPL';
import { TriggerActionDetailsBean } from './TriggerActionDetailsBean';
import { HttpFile } from '../http/http';

export class PlayListServiceBean {
    'id'?: number;
    'plName'?: string;
    'loop'?: boolean;
    'defaultPl'?: boolean;
    'lastModifiedTime'?: string;
    'items'?: Array<BCMSITEMPL>;
    'triggerActionDetailsBean'?: TriggerActionDetailsBean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "plName",
            "baseName": "plName",
            "type": "string",
            "format": ""
        },
        {
            "name": "loop",
            "baseName": "loop",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "defaultPl",
            "baseName": "defaultPl",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastModifiedTime",
            "baseName": "lastModifiedTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<BCMSITEMPL>",
            "format": ""
        },
        {
            "name": "triggerActionDetailsBean",
            "baseName": "triggerActionDetailsBean",
            "type": "TriggerActionDetailsBean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlayListServiceBean.attributeTypeMap;
    }

    public constructor() {
    }
}

