/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RegisterPlayItemStatisticsRequest {
    'playlistItemId'?: number;
    'monitorExternalId'?: string;
    'stationId'?: number;
    'time'?: number;
    'uniqueKey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "playlistItemId",
            "baseName": "playlistItemId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "monitorExternalId",
            "baseName": "monitorExternalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "stationId",
            "baseName": "stationId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "uniqueKey",
            "baseName": "uniqueKey",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RegisterPlayItemStatisticsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

