/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConfigServiceBean } from './ConfigServiceBean';
import { HttpFile } from '../http/http';

export class SaveConfigRequest {
    'configs': Array<ConfigServiceBean>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "configs",
            "baseName": "configs",
            "type": "Array<ConfigServiceBean>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SaveConfigRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

