/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StatisticsUserSatisfaction {
    'userId'?: string;
    'userInteractionType'?: string;
    'userInteractionValue'?: string;
    'createdTime'?: Date;
    'vorgangId'?: string;
    'kasseId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "userInteractionType",
            "baseName": "userInteractionType",
            "type": "string",
            "format": ""
        },
        {
            "name": "userInteractionValue",
            "baseName": "userInteractionValue",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdTime",
            "baseName": "createdTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "vorgangId",
            "baseName": "vorgangId",
            "type": "string",
            "format": ""
        },
        {
            "name": "kasseId",
            "baseName": "kasseId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StatisticsUserSatisfaction.attributeTypeMap;
    }

    public constructor() {
    }
}

