/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StatisticsMediaPlay {
    'playlistItemId'?: number;
    'playlistItemFile'?: string;
    'playlistId'?: number;
    'playlistName'?: string;
    'monitorId'?: number;
    'monitorName'?: string;
    'stationId'?: number;
    'stationName'?: string;
    'actionTime'?: Date;
    'countNum'?: number;
    'vorgangId'?: string;
    'kasseId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "playlistItemId",
            "baseName": "playlistItemId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "playlistItemFile",
            "baseName": "playlistItemFile",
            "type": "string",
            "format": ""
        },
        {
            "name": "playlistId",
            "baseName": "playlistId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "playlistName",
            "baseName": "playlistName",
            "type": "string",
            "format": ""
        },
        {
            "name": "monitorId",
            "baseName": "monitorId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "monitorName",
            "baseName": "monitorName",
            "type": "string",
            "format": ""
        },
        {
            "name": "stationId",
            "baseName": "stationId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "stationName",
            "baseName": "stationName",
            "type": "string",
            "format": ""
        },
        {
            "name": "actionTime",
            "baseName": "actionTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "countNum",
            "baseName": "countNum",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "vorgangId",
            "baseName": "vorgangId",
            "type": "string",
            "format": ""
        },
        {
            "name": "kasseId",
            "baseName": "kasseId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StatisticsMediaPlay.attributeTypeMap;
    }

    public constructor() {
    }
}

