/**
 * KTI - CMS REST API
 * KTI - CMS REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cristian.szep@kronsoft.ro
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerServiceBean } from './CustomerServiceBean';
import { MonitorServiceBean } from './MonitorServiceBean';
import { HttpFile } from '../http/http';

export class StationServiceBean {
    'id'?: number;
    'stationName'?: string;
    'computerName'?: string;
    'customerServiceBean'?: CustomerServiceBean;
    'monitors'?: Array<MonitorServiceBean>;
    'hostName'?: string;
    'port'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "stationName",
            "baseName": "stationName",
            "type": "string",
            "format": ""
        },
        {
            "name": "computerName",
            "baseName": "computerName",
            "type": "string",
            "format": ""
        },
        {
            "name": "customerServiceBean",
            "baseName": "customerServiceBean",
            "type": "CustomerServiceBean",
            "format": ""
        },
        {
            "name": "monitors",
            "baseName": "monitors",
            "type": "Array<MonitorServiceBean>",
            "format": ""
        },
        {
            "name": "hostName",
            "baseName": "hostName",
            "type": "string",
            "format": ""
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return StationServiceBean.attributeTypeMap;
    }

    public constructor() {
    }
}

